import Head from 'next/head';
import styles from '../styles/Home.module.css';

const FIREFLIES_QUANTITY = 15;

const firefliesElementsRenderer = (quantity) => {
  const array = [];
  for (let i = 0; i < quantity; i++) {
    array.push(<div className="firefly"></div>);
  }
  return array;
};

export default function Home() {
  const fireflyElements = firefliesElementsRenderer(FIREFLIES_QUANTITY);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-white absolute top-1/2 left-1/2">
        <div></div>
        {fireflyElements}
      </main>
    </div>
  );
}
