import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Navbar from '../components/Navbar';

const FIREFLIES_QUANTITY = 15;

const firefliesElementsRenderer = (quantity) => {
  const array = [];
  for (let i = 0; i < quantity; i++) {
    array.push(<div className="firefly"></div>);
  }
  return array;
};

export default function Home() {
  const fireflyElements = firefliesElementsRenderer(FIREFLIES_QUANTITY);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <section className="lendingPage">
          <Header />
          <Navbar />
          {fireflyElements}
        </section>
        <section>
          <div className="container bg-bgDark-100 min-h-screen">
            <p>hi</p>
          </div>
        </section>
      </main>
    </div>
  );
}
